name: Update docs
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger docs workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: unifyai
          repo: ivy
          workflow_file_name: docs.yml
          github_token: ${{ secrets.IVY_BRANCH_TOKEN }}
